# ===== DEV PROFILE — MySQL =====

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/dev_report_engine?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=report_engine
spring.datasource.password=pass_report_engine
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Report Storage
app.report.storage.path=./reports

# Logging
logging.level.com.singgih=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.root=INFO
