# ===== PROD PROFILE — Oracle =====

# Database
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/prod_report_engine
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=report_engine
spring.datasource.password=ceritanya_passwordprod
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate

# Report Storage
app.report.storage.path=./reports

# Logging
logging.level.com.singgih=INFO
logging.level.org.springframework.web=WARN
logging.level.root=WARN
